/**
 * Catalogue complet des morceaux pour Breachy
 * Relie chaque fichier audio / MIDI / partition à ses métadonnées et son filtre
 */
import { musicCatalog } from "../data/musicData";

// Import automatique de toutes les URLs des fichiers MIDI dans src/resources/audio/
const midiUrls = import.meta.glob("./audio/*.mid", {
  eager: true,
  query: "?url",
  import: "default",
});

function getMidiUrl(filename) {
  return midiUrls[`./audio/${filename}`] || null;
}

export const songsCatalog = [
  // --- NOUVEAUX MORCEAUX TÉLÉCHARGÉS ---
  {
    id: "abicycle",
    title: "abicycle",
    artist: "Harry Dacre (Daisy Bell)",
    category: "Enfants",
    level: "Débutant",
    duration: "2:34",
    image: "https://images.unsplash.com/photo-1485965120184-e220f721d03e?auto=format&fit=crop&w=400&q=80",
    musicItem: { id: "abicycle", label: "abicycle", type: "midi", url: getMidiUrl("abicycle.mid") },
    file: "abicycle.mid",
  },
  {
    id: "vivalavi",
    title: "Viva La Vida",
    artist: "Coldplay",
    category: "Pop",
    level: "Intermédiaire",
    duration: "3:42",
    image: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=400&q=80",
    musicItem: { id: "vivalavi", label: "Viva La Vida", type: "midi", url: getMidiUrl("vivalavi.mid") },
    file: "vivalavi.mid",
  },
  {
    id: "take-on-me",
    title: "Take on Me",
    artist: "A-ha",
    category: "Pop",
    level: "Intermédiaire",
    duration: "3:44",
    image: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=400&q=80",
    musicItem: { id: "take-on-me", label: "Take on Me", type: "midi", url: getMidiUrl("Aha__Take_on_me.mid") },
    file: "Aha__Take_on_me.mid",
  },
  {
    id: "bohemian-rhapsody",
    title: "Bohemian Rhapsody",
    artist: "Queen",
    category: "Pop",
    level: "Classique",
    duration: "5:28",
    image: "https://images.unsplash.com/photo-1501386761578-eac5c94b800a?auto=format&fit=crop&w=400&q=80",
    musicItem: { id: "bohemian-rhapsody", label: "Bohemian Rhapsody", type: "midi", url: getMidiUrl("Queen_Bohemian_Rhapsody.mid") },
    file: "Queen_Bohemian_Rhapsody.mid",
  },
  {
    id: "show-must-go-on",
    title: "The Show Must Go On",
    artist: "Queen",
    category: "Pop",
    level: "Intermédiaire",
    duration: "3:58",
    image: "https://images.unsplash.com/photo-1465847899084-d164df4dedc6?auto=format&fit=crop&w=400&q=80",
    musicItem: { id: "show-must-go-on", label: "The Show Must Go On", type: "midi", url: getMidiUrl("show_must_go_on_Queen.mid") },
    file: "show_must_go_on_Queen.mid",
  },
  {
    id: "iljouait",
    title: "Il jouait du piano debout",
    artist: "France Gall",
    category: "Variété",
    level: "Intermédiaire",
    duration: "4:34",
    image: "https://images.unsplash.com/photo-1520523839897-bd0b52f945a0?auto=format&fit=crop&w=400&q=80",
    musicItem: { id: "iljouait", label: "Il jouait du piano debout", type: "midi", url: getMidiUrl("iljouait.mid") },
    file: "iljouait.mid",
  },
  {
    id: "cabanedu",
    title: "La cabane du pêcheur",
    artist: "Francis Cabrel",
    category: "Variété",
    level: "Intermédiaire",
    duration: "4:56",
    image: "https://images.unsplash.com/photo-1510312305653-8ed496efae75?auto=format&fit=crop&w=400&q=80",
    musicItem: { id: "cabanedu", label: "La cabane du pêcheur", type: "midi", url: getMidiUrl("cabanedu.mid") },
    file: "cabanedu.mid",
  },
  {
    id: "elleecou",
    title: "Elle écoute pousser les fleurs",
    artist: "Francis Cabrel",
    category: "Variété",
    level: "Intermédiaire",
    duration: "2:54",
    image: "https://images.unsplash.com/photo-1490750967868-88aa4486c946?auto=format&fit=crop&w=400&q=80",
    musicItem: { id: "elleecou", label: "Elle écoute pousser les fleurs", type: "midi", url: getMidiUrl("elleecou.mid") },
    file: "elleecou.mid",
  },
  {
    id: "maison",
    title: "San Francisco (La maison bleue)",
    artist: "Maxime Le Forestier",
    category: "Variété",
    level: "Intermédiaire",
    duration: "2:49",
    image: "https://images.unsplash.com/photo-1506146332389-18140dc7b2fb?auto=format&fit=crop&w=400&q=80",
    musicItem: { id: "maison", label: "San Francisco", type: "midi", url: getMidiUrl("maison.mid") },
    file: "maison.mid",
  },
  {
    id: "aupresd2",
    title: "Auprès de mon arbre",
    artist: "Georges Brassens",
    category: "Variété",
    level: "Débutant",
    duration: "3:09",
    image: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=400&q=80",
    musicItem: { id: "aupresd2", label: "Auprès de mon arbre", type: "midi", url: getMidiUrl("aupresd2.mid") },
    file: "aupresd2.mid",
  },
  {
    id: "beachbab",
    title: "Beach Baby",
    artist: "The First Class",
    category: "Pop",
    level: "Intermédiaire",
    duration: "3:58",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=400&q=80",
    musicItem: { id: "beachbab", label: "Beach Baby", type: "midi", url: getMidiUrl("beachbab.mid") },
    file: "beachbab.mid",
  },
  {
    id: "vienssur",
    title: "Viens sur la montagne",
    artist: "Marie Laforêt",
    category: "Variété",
    level: "Débutant",
    duration: "2:25",
    image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=400&q=80",
    musicItem: { id: "vienssur", label: "Viens sur la montagne", type: "midi", url: getMidiUrl("vienssur.mid") },
    file: "vienssur.mid",
  },
  {
    id: "aliceago",
    title: "All in the Golden Afternoon",
    artist: "Alice au pays des merveilles (Disney)",
    category: "Films & Séries",
    level: "Intermédiaire",
    duration: "1:33",
    image: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=400&q=80",
    musicItem: { id: "aliceago", label: "All in the Golden Afternoon", type: "midi", url: getMidiUrl("aliceago.mid") },
    file: "aliceago.mid",
  },
  {
    id: "alicewon",
    title: "Alice in Wonderland",
    artist: "Alice au pays des merveilles (Disney)",
    category: "Films & Séries",
    level: "Intermédiaire",
    duration: "1:21",
    image: "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=400&q=80",
    musicItem: { id: "alicewon", label: "Alice in Wonderland", type: "midi", url: getMidiUrl("alicewon.mid") },
    file: "alicewon.mid",
  },
  {
    id: "icecastl",
    title: "Through the Eyes of Love",
    artist: "Theme from Ice Castles (Marvin Hamlisch)",
    category: "Films & Séries",
    level: "Intermédiaire",
    duration: "3:53",
    image: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=400&q=80",
    musicItem: { id: "icecastl", label: "Through the Eyes of Love", type: "midi", url: getMidiUrl("icecastl.mid") },
    file: "icecastl.mid",
  },
  {
    id: "sorciere",
    title: "L'Apprenti Sorcier",
    artist: "Paul Dukas (Fantasia)",
    category: "Films & Séries",
    level: "Classique",
    duration: "4:11",
    image: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=400&q=80",
    musicItem: { id: "sorciere", label: "L'Apprenti Sorcier", type: "midi", url: getMidiUrl("sorciere.mid") },
    file: "sorciere.mid",
  },
  {
    id: "lhiver",
    title: "L'Hiver - Largo",
    artist: "A. Vivaldi (Les Quatre Saisons)",
    category: "Classique",
    level: "Classique",
    duration: "2:08",
    image: "https://images.unsplash.com/photo-1491557345352-5929e343eb89?auto=format&fit=crop&w=400&q=80",
    musicItem: { id: "lhiver", label: "L'Hiver (Vivaldi)", type: "midi", url: getMidiUrl("lhiver.mid") },
    file: "lhiver.mid",
  },
  {
    id: "noisette",
    title: "Valse des Fleurs (Casse-Noisette)",
    artist: "P. Tchaïkovski",
    category: "Classique",
    level: "Classique",
    duration: "1:07",
    image: "https://images.unsplash.com/photo-1543258103-a62bd961302b?auto=format&fit=crop&w=400&q=80",
    musicItem: { id: "noisette", label: "Casse-Noisette", type: "midi", url: getMidiUrl("noisette.mid") },
    file: "noisette.mid",
  },
  {
    id: "jeuxint",
    title: "Jeux Interdits (Romance)",
    artist: "Anonyme",
    category: "Classique",
    level: "Débutant",
    duration: "1:05",
    image: "https://images.unsplash.com/photo-1510915361894-db8b60106cb1?auto=format&fit=crop&w=400&q=80",
    musicItem: { id: "jeuxint", label: "Jeux Interdits", type: "midi", url: getMidiUrl("jeuxint.mid") },
    file: "jeuxint.mid",
  },
  {
    id: "berceuse",
    title: "Berceuse classique",
    artist: "Traditionnel / Classique",
    category: "Classique",
    level: "Débutant",
    duration: "3:49",
    image: "https://images.unsplash.com/photo-1511192336575-5a79af67a629?auto=format&fit=crop&w=400&q=80",
    musicItem: { id: "berceuse", label: "Berceuse", type: "midi", url: getMidiUrl("berceuse.mid") },
    file: "berceuse.mid",
  },
  {
    id: "unelarme",
    title: "Une Larme",
    artist: "Modeste Moussorgski",
    category: "Classique",
    level: "Classique",
    duration: "3:18",
    image: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=400&q=80",
    musicItem: { id: "unelarme", label: "Une Larme", type: "midi", url: getMidiUrl("unelarme.mid") },
    file: "unelarme.mid",
  },
  {
    id: "leranz",
    title: "Le Ranz des Vaches",
    artist: "Traditionnel",
    category: "Classique",
    level: "Débutant",
    duration: "1:39",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=400&q=80",
    musicItem: { id: "leranz", label: "Le Ranz des Vaches", type: "midi", url: getMidiUrl("leranz.mid") },
    file: "leranz.mid",
  },
  {
    id: "nuits",
    title: "Les Nuits de Moscou",
    artist: "Traditionnel",
    category: "Classique",
    level: "Intermédiaire",
    duration: "1:28",
    image: "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=400&q=80",
    musicItem: { id: "nuits", label: "Les Nuits de Moscou", type: "midi", url: getMidiUrl("nuits.mid") },
    file: "nuits.mid",
  },
  {
    id: "etoiles",
    title: "Ah ! vous dirai-je, maman",
    artist: "Comptine (Brille brille petite étoile)",
    category: "Enfants",
    level: "Débutant",
    duration: "2:46",
    image: "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=400&q=80",
    musicItem: { id: "etoiles", label: "Ah vous dirai-je maman", type: "midi", url: getMidiUrl("etoiles.mid") },
    file: "etoiles.mid",
  },
  {
    id: "alapeche",
    title: "À la pêche aux moules",
    artist: "Comptine traditionnelle",
    category: "Enfants",
    level: "Débutant",
    duration: "0:14",
    image: "https://images.unsplash.com/photo-1516627145497-ae6968895b74?auto=format&fit=crop&w=400&q=80",
    musicItem: { id: "alapeche", label: "À la pêche aux moules", type: "midi", url: getMidiUrl("alapeche.mid") },
    file: "alapeche.mid",
  },
  {
    id: "bercefee",
    title: "Highland Fairy Lullaby",
    artist: "Berceuse féerique",
    category: "Enfants",
    level: "Débutant",
    duration: "2:33",
    image: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=400&q=80",
    musicItem: { id: "bercefee", label: "Highland Fairy Lullaby", type: "midi", url: getMidiUrl("bercefee.mid") },
    file: "bercefee.mid",
  },
  {
    id: "carousel",
    title: "Le Carrousel",
    artist: "Musique de manège",
    category: "Enfants",
    level: "Débutant",
    duration: "3:04",
    image: "https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?auto=format&fit=crop&w=400&q=80",
    musicItem: { id: "carousel", label: "Le Carrousel", type: "midi", url: getMidiUrl("carousel.mid") },
    file: "carousel.mid",
  },
  {
    id: "cloches",
    title: "Les Cloches du hameau",
    artist: "Chant de Noël traditionnel",
    category: "Noël",
    level: "Débutant",
    duration: "1:55",
    image: "https://images.unsplash.com/photo-1512389142860-9c449e58a543?auto=format&fit=crop&w=400&q=80",
    musicItem: { id: "cloches", label: "Les Cloches du hameau", type: "midi", url: getMidiUrl("cloches.mid") },
    file: "cloches.mid",
  },
  {
    id: "promenad",
    title: "Promenade en traîneau (Sleigh Ride)",
    artist: "Leroy Anderson",
    category: "Noël",
    level: "Intermédiaire",
    duration: "2:51",
    image: "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=400&q=80",
    musicItem: { id: "promenad", label: "Promenade en traîneau", type: "midi", url: getMidiUrl("promenad.mid") },
    file: "promenad.mid",
  },
  {
    id: "xmasfair",
    title: "Christmas Fairies",
    artist: "Chant féerique de Noël",
    category: "Noël",
    level: "Débutant",
    duration: "1:04",
    image: "https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?auto=format&fit=crop&w=400&q=80",
    musicItem: { id: "xmasfair", label: "Christmas Fairies", type: "midi", url: getMidiUrl("xmasfair.mid") },
    file: "xmasfair.mid",
  },
  {
    id: "mario",
    title: "Super Mario Bros",
    artist: "Koji Kondo (Nintendo)",
    category: "Films & Séries",
    level: "Débutant",
    duration: "0:25",
    image: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=400&q=80",
    musicItem: musicCatalog.find((m) => m.id === "mario"),
    file: "mario.txt",
  },
  {
    id: "pirate",
    title: "Pirates des Caraïbes",
    artist: "Hans Zimmer & Klaus Badelt",
    category: "Films & Séries",
    level: "Intermédiaire",
    duration: "1:45",
    image: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=400&q=80",
    musicItem: musicCatalog.find((m) => m.id === "pirate"),
    file: "pirate.txt",
  },
  {
    id: "fur-elise",
    title: "Für Elise",
    artist: "L. van Beethoven",
    category: "Classique",
    level: "Classique",
    duration: "3:02",
    image: "https://images.unsplash.com/photo-1520523839897-bd0b52f945a0?auto=format&fit=crop&w=400&q=80",
    audio: "https://upload.wikimedia.org/wikipedia/commons/1/18/Fur_Elise.ogg",
  },
  {
    id: "clair-de-lune",
    title: "Clair de lune",
    artist: "C. Debussy",
    category: "Classique",
    level: "Classique",
    duration: "5:12",
    image: "https://images.unsplash.com/photo-1470252649378-9c29740c9fa8?auto=format&fit=crop&w=400&q=80",
    audio: "https://upload.wikimedia.org/wikipedia/commons/2/21/Debussy_-_Clair_de_lune.ogg",
  },
];

export default songsCatalog;
