/**
 * Catalogue des morceaux pour Breachy
 * Relie chaque morceau à ses métadonnées, son fichier audio dans src/resources/audio/
 * et ses données de partition dans src/resources/data/
 */

export const songsCatalog = [
  {
    id: "au-clair-de-la-lune",
    title: "Au clair de la lune",
    artist: "Traditionnel",
    level: "Débutant",
    duration: "2:36",
    image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=300&q=80",
    audio: "/resources/audio/au-clair-de-la-lune.mp3",
    scoreText: "au-clair-de-la-lune.txt",
    // Exemple d'audio de secours si le fichier local n'est pas encore déposé
    fallbackAudio: "https://cdn.freesound.org/previews/612/612610_5674468-lq.mp3",
  },
  {
    id: "frere-jacques",
    title: "Frère Jacques",
    artist: "Traditionnel",
    level: "Débutant",
    duration: "1:40",
    image: "https://images.unsplash.com/photo-1516627145497-ae6968895b74?auto=format&fit=crop&w=300&q=80",
    audio: "/resources/audio/frere-jacques.mp3",
    scoreText: "frere-jacques.txt",
    fallbackAudio: "https://cdn.freesound.org/previews/612/612610_5674468-lq.mp3",
  },
  {
    id: "let-it-be",
    title: "Let It Be",
    artist: "The Beatles",
    level: "Intermédiaire",
    duration: "4:03",
    image: "https://images.unsplash.com/photo-1449824913935-59a10b8d2000?auto=format&fit=crop&w=300&q=80",
    audio: "/resources/audio/let-it-be.mp3",
    scoreText: "let-it-be.txt",
    fallbackAudio: "https://cdn.freesound.org/previews/612/612610_5674468-lq.mp3",
  },
  {
    id: "comptine-d-un-autre-ete",
    title: "Comptine d'un autre été",
    artist: "Yann Tiersen",
    level: "Intermédiaire",
    duration: "3:18",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=300&q=80",
    audio: "/resources/audio/comptine-d-un-autre-ete.mp3",
    scoreText: "comptine-d-un-autre-ete.txt",
    fallbackAudio: "https://cdn.freesound.org/previews/612/612610_5674468-lq.mp3",
  },
  {
    id: "la-vie-en-rose",
    title: "La Vie en rose",
    artist: "Édith Piaf",
    level: "Intermédiaire",
    duration: "3:22",
    image: "https://images.unsplash.com/photo-1490750967868-88aa4486c946?auto=format&fit=crop&w=300&q=80",
    audio: "/resources/audio/la-vie-en-rose.mp3",
    scoreText: "la-vie-en-rose.txt",
    fallbackAudio: "https://cdn.freesound.org/previews/612/612610_5674468-lq.mp3",
  },
  {
    id: "fur-elise",
    title: "Für Elise",
    artist: "L. van Beethoven",
    level: "Classique",
    duration: "3:02",
    image: "https://images.unsplash.com/photo-1520523839897-bd0b52f945a0?auto=format&fit=crop&w=300&q=80",
    audio: "/resources/audio/fur-elise.mp3",
    scoreText: "fur-elise.txt",
    fallbackAudio: "https://upload.wikimedia.org/wikipedia/commons/1/18/Fur_Elise.ogg",
  },
  {
    id: "clair-de-lune",
    title: "Clair de lune",
    artist: "C. Debussy",
    level: "Classique",
    duration: "5:12",
    image: "https://images.unsplash.com/photo-1470252649378-9c29740c9fa8?auto=format&fit=crop&w=300&q=80",
    audio: "/resources/audio/clair-de-lune.mp3",
    scoreText: "clair-de-lune.txt",
    fallbackAudio: "https://upload.wikimedia.org/wikipedia/commons/2/21/Debussy_-_Clair_de_lune.ogg",
  },
  {
    id: "can-you-feel-the-love-tonight",
    title: "Can you feel the love tonight",
    artist: "Elton John (Le Roi Lion)",
    level: "Intermédiaire",
    duration: "4:10",
    image: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=300&q=80",
    audio: "/resources/audio/can-you-feel-the-love-tonight.mp3",
    scoreText: "can-you-feel-the-love-tonight.txt",
    fallbackAudio: "https://cdn.freesound.org/previews/612/612610_5674468-lq.mp3",
  },
  {
    id: "hallelujah",
    title: "Hallelujah",
    artist: "Leonard Cohen",
    level: "Intermédiaire",
    duration: "5:08",
    image: "https://images.unsplash.com/photo-1524650359799-842906ca1c06?auto=format&fit=crop&w=300&q=80",
    audio: "/resources/audio/hallelujah.mp3",
    scoreText: "hallelujah.txt",
    fallbackAudio: "https://cdn.freesound.org/previews/612/612610_5674468-lq.mp3",
  },
  {
    id: "river-flows-in-you",
    title: "River Flows in You",
    artist: "Yiruma",
    level: "Intermédiaire",
    duration: "4:02",
    image: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=300&q=80",
    audio: "/resources/audio/river-flows-in-you.mp3",
    scoreText: "river-flows-in-you.txt",
    fallbackAudio: "https://cdn.freesound.org/previews/612/612610_5674468-lq.mp3",
  },
  {
    id: "joyeux-anniversaire",
    title: "Joyeux anniversaire",
    artist: "Traditionnel",
    level: "Débutant",
    duration: "1:12",
    image: "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?auto=format&fit=crop&w=300&q=80",
    audio: "/resources/audio/joyeux-anniversaire.mp3",
    scoreText: "joyeux-anniversaire.txt",
    fallbackAudio: "https://cdn.freesound.org/previews/612/612610_5674468-lq.mp3",
  },
  {
    id: "bella-ciao",
    title: "Bella Ciao",
    artist: "Traditionnel",
    level: "Intermédiaire",
    duration: "3:45",
    image: "https://images.unsplash.com/photo-1500462918059-b1a0cb512f1d?auto=format&fit=crop&w=300&q=80",
    audio: "/resources/audio/bella-ciao.mp3",
    scoreText: "bella-ciao.txt",
    fallbackAudio: "https://cdn.freesound.org/previews/612/612610_5674468-lq.mp3",
  },
];

export default songsCatalog;
